### ISSUE TITLE
Usage instructions not working as intended

### ISSUE THREAD

**Issue by donovanglover** [veelenga/rainbow-spec#1]
Hello,

Thanks for spending your time to create this shard; however, I would like to point out that the usage instructions do not work.

Running `shards install`  with the default usage instructions, I get:

```
Failed git ls-tree -r --full-tree --name-only v0.1.0 -- shard.yml ().
Maybe a commit, branch or file doesn't exist?
```

To get the shard to install, I had to bypass tag versioning and add `branch: master` to my `shard.yml`.

**Comment by veelenga** [comment]
@GloverDonovan that was a mistake in a release name (not semver). Please approve if it works now.

**Comment by donovanglover** [comment]
It works now, thanks!
